export default {
    products: [
        {
            _id: '0',
            category: 'Appetizers',
            name: 'Garlic Bread',
            image: '/images/gb.jpg',
            price: 18,
            rating: 4.5,
            brand: 'Something',
            numReviews: 10,
            countInStock: 15,
        },
        {
            _id: '1',
            category: 'Main Course',
            name: 'Supreme Garlic Bread',
            image: '/images/gb.jpg',
            price: 25,
            rating: 4.8,
            brand: 'Something',
            numReviews: 18,
            countInStock: 14,
        },
        {
            _id: '2',
            category: 'Main Course',
            name: 'Pide (Turkish Pizza)',
            image: '/images/gb.jpg',
            price: 32,
            rating: 4,
            brand: 'Something',
            numReviews: 8,
            countInStock: 12,
        },
        {
            _id: '3',
            category: 'Appetizers',
            name: 'Mozzerrella Sticks',
            image: '/images/gb.jpg',
            price: 10,
            rating: 3.5,
            brand: 'Something',
            numReviews: 3,
            countInStock: 9,
        },
        {
            _id: '4',
            category: 'Appetizers',
            name: 'Patato Party',
            image: '/images/gb.jpg',
            price: 10,
            rating: 3.5,
            brand: 'Something',
            numReviews: 3,
            countInStock: 10,
        }
    ]
}